export const EDIT_NEW_MOVIE_TITLE = "EDIT_NEW_MOVIE_TITLE";
export const EDIT_NEW_MOVIE_DIRECTOR = "EDIT_NEW_MOVIE_DIRECTOR";
export const EDIT_NEW_MOVIE_YEAR = "EDIT_NEW_MOVIE_YEAR";
export const EDIT_NEW_MOVIE_RATING = "EDIT_NEW_MOVIE_RATING";
